- name: install npm modules
  npm: name={{item}} global=yes state=present
  with_items:
    - gulp
    - bower

- name: install npm modules in project root
  npm: path=/vagrant state=present
  ignore_errors: true
